Render graph with ranked nodes
karl-home/karl-ui pull request #6
Opened 2021-06-29 07:24 UTC by henryweng03

When we call setGraphFormat, the coordinates for where the nodes should be located are all pre-calculated. We use DP and recursion to find depth (see getNodeDepth() in graph.ts) of each node and use DP and multiple level-order traversals to find horizontal position (see getLevelOrderTraversal() in graph.ts) of each node. 

Additionally, add_sensor, addModuleWithId, and other related functions have been modified to allow us to pass in coordinates for where the nodes should be located (this was necessary because coordinates are pre-calculated instead of using _nextNodeLocation()). 

Nodes that do not have any edges, however, still use _nextNodeLocation(), but the function has been modified solely for the purpose of finding the coordinates of nodes that do not have edges.

2021-07-01 18:29 UTC, ygina requested changes
The graphs are looking good! Left a few comments, mostly on removing unused code and deleting magic numbers. And one about rendering graphs on slightly smaller screen sizes.

2021-07-01 18:29 UTC, ygina commented on src/graph.ts
> +import { find } from 'lodash';
What is this import used for?

2021-07-01 18:29 UTC, ygina commented on src/graph.ts
> +    this.addModuleWithId(mod, id, -1, -1)
Use optional or default parameters instead of magic numbers.

2021-07-01 18:29 UTC, ygina commented on src/graph.ts
> +    for(let i = 0; i < f.sensors.length; i++){
Can you modularize some of this code? i.e., creating a function that just calculates the adjacency matrix, creating a separate interface for any functions that are related to calculating node positions.

2021-07-01 18:29 UTC, ygina commented on src/main/graph_html.ts
>    let col = nnodes - row * COLS
Delete dead code lines 20-21 and any unused constants such as `nnodes`.

2021-07-01 18:29 UTC, ygina commented on src/sidebar/sensor_html.ts
> +      g.add_sensor(sensors[sensorId].sensor, -1, -1, 1, -1)
Use optional parameters.

2021-07-01 18:29 UTC, ygina commented on src/graph.ts
> +    console.log(this.levelOrder)
Remove debug log.

2021-07-01 18:29 UTC, ygina commented on src/graph.ts
> +        console.log(this.levelOrder)
Remove debug logs.

2021-07-01 18:29 UTC, ygina commented on src/main/graph_html.ts
> +    left: 900,
Can you create named constants for these numbers such as `100`, `900`, `-30`?

2021-07-01 18:29 UTC, ygina commented on src/graph.ts
> +    vCoordUnconnectedNode.coord = 0
Is there a reason this is `0` and the initial value of `coord` is `-30`?

2021-07-01 18:29 UTC, ygina commented on src/main/graph_html.ts
> +    left: 900,
Also, at `900`, unconnected nodes get covered by the sidebar on my screen unless my browser is at its maximum width. Could we put the unconnected nodes on the left side or something else?

2021-07-13 18:32 UTC, ygina requested changes

2021-07-13 18:32 UTC, ygina commented on src/graph.ts
> +
Is something supposed to go here?

2021-07-13 18:32 UTC, ygina commented on src/graph.ts
> +    if(typeof top == undefined){
`typeof top == 'undefined'` -- JavaScript has horrible edge cases for checking null/undefined equality...

2021-07-13 18:32 UTC, ygina commented on src/main/graph_html.ts
> +  //if top == -1, then go with _nextNodeLocation(), otherwise use
Update comment to correspond to functionality.

2021-07-13 18:32 UTC, ygina commented on src/graph.ts
> +  MAX_WIDTH = 800
Can we delete some of these variables now that they are in `GraphCoord`?

2021-07-13 18:32 UTC, ygina commented on src/graph.ts
> +import { find } from 'lodash';
If the import isn't used, we can probably delete it. :)

2021-07-22 06:38 UTC, henryweng03 reviewed
Changes fixed

2021-07-27 17:59 UTC, ygina approved these changes

2021-07-27 19:21 UTC, merged